name: Post review to twitter
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  post-review:
    runs-on: [ubuntu-latest]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
      - run: npm i
      - run: build
